CREATE TABLE actors (
	id int8 PRIMARY KEY AUTO_INCREMENT,
	name varchar(255)
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE directors (
	id int8 PRIMARY KEY AUTO_INCREMENT,
	name varchar(255) NOT NULL
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE films (
	id int8 PRIMARY KEY AUTO_INCREMENT,
	title varchar(255) NOT NULL,
	director int8 NOT NULL,
	released datetime NOT NULL,
	nominated boolean NOT NULL DEFAULT FALSE,
	FOREIGN KEY (director) REFERENCES directors(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB CHARSET=utf8;

CREATE TABLE film_actors (
	id int8 PRIMARY KEY AUTO_INCREMENT,
	film int8 NOT NULL,
	actor int8 NOT NULL,
	FOREIGN KEY (film) REFERENCES films(id) ON UPDATE CASCADE ON DELETE RESTRICT,
	FOREIGN KEY (actor) REFERENCES actors(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB CHARSET=utf8;
